### ISSUE TITLE
Typescript Error: 'TextEncoder' does not exist on type 'Window'.

### ISSUE THREAD

**Issue by jnaviask** [cosmos/amino-js#1]
Using typescript@3.4.1 and webpack 4.29.6, I get the following error message at compile time:

```
ERROR in [at-loader] ./node_modules/@tendermint/amino-js/src/util.ts:19:33 
    TS2339: Property 'TextEncoder' does not exist on type 'Window'.
```

Any idea how to solve? Thanks!

**Comment by jordansexton** [comment]
Thanks for the report! The repo compiles, lints, and tests with TypeScript, so I'm guessing it's something specific to your tsconfig.json or webpack.config.js.

Are you able to provide a reproduction of the issue as a repo? I'm happy to test it out.

**Comment by jordansexton** [comment]
You can also augment Window like this and the warning should go away:

```typescript
declare global {
    interface Window {
        TextEncoder: { new (): { decode (bytes: Uint8Array): string } };
        TextDecoder: { new (): { encode (string: string): Uint8Array } };
    }
}
```

The actual API of [TextEncoder](https://developer.mozilla.org/en-US/docs/Web/API/TextEncoder) and [TextDecoder](https://developer.mozilla.org/en-US/docs/Web/API/TextDecoder) are different, but these minimal interfaces are [what util.ts declares](https://github.com/cosmos/amino-js/blob/1d7567307a0639e170c807c384c1ff810d30bd65/src/util.ts#L1-L2).

**Comment by jnaviask** [comment]
Augmenting the window as suggested worked, thank you!

**Comment by joticajulian** [comment]
I had this issue in a different project and I solved it by adding `"lib": ["ES6", "DOM"],` in tsconfig.json.
Example:
```
{
  "extends": "@tsconfig/node14/tsconfig.json",
  "compilerOptions": {
    "resolveJsonModule": true,
    "allowSyntheticDefaultImports": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "declaration": false,
    "module": "CommonJS",
    "sourceMap": true,
    "lib": ["ES6", "DOM"],
    "incremental": true,
    "strict": false,
    "outDir": "./dist",
    "baseUrl": "./"
  },
  "include": ["src/**/**"]
}
```
